using Microsoft.CodeAnalysis;

namespace AStarDev.SourceGenerators.StrongTypeCodeGeneration;

internal static class StrongTypeCodeGenerator
{
    private const string AutoGeneratedComment = "// <auto-generated/>";
    private const string Usings = "using System;\nusing System.Collections.Generic;";

    public static string Generate(StrongTypeModel model)
    {
        string ns = model.Namespace is null ? string.Empty : $"namespace {model.Namespace};";
        string accessibility = model.Accessibility == Accessibility.Internal ? "internal" : "public";
        string underlying = GetRequiredUnderlyingType(model);
        string typeKind = model.IsValueType ? "readonly partial record struct" : "sealed partial record";
        string documentation = $"/// <summary>A strongly-typed wrapper around a <see cref=\"{underlying}\"/> value.</summary>\n/// <param name=\"Value\">The underlying value.</param>";

        string code = $"{AutoGeneratedComment}\n\n{Usings}\n\n{(string.IsNullOrEmpty(ns) ? string.Empty : ns)}\n\n{documentation}\n{accessibility} {typeKind} {model.ModelName}({underlying} Value)\n";
        code += $"{{\n    /// <inheritdoc />\n    public static implicit operator {model.ModelName}({underlying} value) => new {model.ModelName}(value);\n\n    /// <inheritdoc />\n    public static implicit operator {underlying}({model.ModelName} strongType) => strongType.Value;\n}}";

        return code;
    }

    private static string GetRequiredUnderlyingType(StrongTypeModel model)
    {
        string underlying = model.UnderlyingTypeDisplay;
        if (string.IsNullOrEmpty(underlying))
            return "System.Guid";

        if (underlying.IndexOf('.') < 0)
        {
            switch (underlying)
            {
                case "Guid":
                    underlying = "System.Guid";
                    break;
                case "string":
                    underlying = "System.String";
                    break;
                case "int":
                    underlying = "System.Int32";
                    break;
                case "long":
                    underlying = "System.Int64";
                    break;
            }
        }

        return underlying;
    }
}
