// <auto-generated />
using System;
using AStarDev.ControlDb.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AStarDev.ControlDb.Persistence.Migrations
{
    [DbContext(typeof(ControlDbContext))]
    [Migration("20260923091659_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("AStarDev.ControlDb.Persistence.ScrapeConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("HotWallpapers")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SearchCategoryPrefix")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SearchCategorySuffix")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SiteUrl")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TopWallpapers")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ScrapeConfigurations");
                });
#pragma warning restore 612, 618
        }
    }
}
